# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-10 18:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_show_theatre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='theatre',
        ),
    ]
