# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-11 07:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20170510_1941'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together=set([('no', 'show', 'seat_type')]),
        ),
    ]
