# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-27 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dashboard',
            old_name='name',
            new_name='username',
        ),
        migrations.AddField(
            model_name='dashboard',
            name='about',
            field=models.TextField(default='default about text'),
        ),
    ]
