# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-27 10:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20170227_1024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dashboard',
            old_name='name',
            new_name='username',
        ),
    ]
