# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-27 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20170227_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='location',
            field=models.CharField(default='location default text', max_length=200),
        ),
    ]
