# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-27 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_dashboard_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='worktitle',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='location',
            field=models.CharField(blank=True, default='location default text', max_length=200),
        ),
    ]
