# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-27 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20170227_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='worktitle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
